project_id = "qzrvctpwefhmcduariuw"

[functions.add-to-google-group]
verify_jwt = false

[functions.bulk-sync-google-group]
verify_jwt = false

[functions.cashfree-webhook]
verify_jwt = false

[functions.reconcile-payments]
verify_jwt = false
